[pytest]
# Permite importar "utils" desde los tests sin problemas de rutas
pythonpath = .
testpaths = tests
markers =
    smoke: pruebas críticas y rápidas
    login: pruebas del flujo de autenticación
    catalogo: pruebas de navegación y verificación del inventario
    carrito: pruebas de interacción con el carrito